# Generated by Django 6.0.1 on 2026-01-18 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Hakkımda')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Konum')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profil Resmi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
