# Generated by Django 6.0.1 on 2026-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('requester', 'Requester'), ('employee', 'Employee')], default='requester', max_length=20, verbose_name='Kullanıcı Rolü'),
        ),
    ]
